services:
  contract-verifier:
    image: secret-contract-verifier
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MONGODB_URI=mongodb://192.168.1.42:27017/comet-scan-demo
    privileged: true  # Needed for Docker-in-Docker

volumes:
  contract-verifier-data:
  mongodb-data: 